---
abstract: 'Framework for compiling tranformations on HTML text'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Transmorgify
provides:
  HTML::Transmorgify:
    file: lib/HTML/Transmorgify.pm
    version: 0.04
  HTML::Transmorgify::Attributes:
    file: lib/HTML/Transmorgify/Attributes.pm
  HTML::Transmorgify::CloseTag:
    file: lib/HTML/Transmorgify.pm
  HTML::Transmorgify::Conditionals:
    file: lib/HTML/Transmorgify/Conditionals.pm
  HTML::Transmorgify::ConditionalsDebug:
    file: lib/HTML/Transmorgify/ConditionalsDebug.pm
  HTML::Transmorgify::Crumbs:
    file: lib/HTML/Transmorgify/Crumbs.pm
  HTML::Transmorgify::Deferred:
    file: lib/HTML/Transmorgify.pm
  HTML::Transmorgify::Exclusive:
    file: lib/HTML/Transmorgify.pm
  HTML::Transmorgify::FormChecksum:
    file: lib/HTML/Transmorgify/FormChecksum.pm
  HTML::Transmorgify::FormDefault:
    file: lib/HTML/Transmorgify/FormDefault.pm
  HTML::Transmorgify::Metatags:
    file: lib/HTML/Transmorgify/Metatags.pm
  HTML::Transmorgify::MutuallyExclusive:
    file: lib/HTML/Transmorgify.pm
  HTML::Transmorgify::ObjectGlue:
    file: lib/HTML/Transmorgify/ObjectGlue.pm
  HTML::Transmorgify::Stack:
    file: lib/HTML/Transmorgify.pm
  HTML::Transmorgify::Symbols:
    file: lib/HTML/Transmorgify/Symbols.pm
  Parse::RecDescent::HTML::Transmorgify::Conditionals:
    file: lib/HTML/Transmorgify/Conditionals.pm
  Parse::RecDescent::HTML::Transmorgify::ConditionalsDebug:
    file: lib/HTML/Transmorgify/ConditionalsDebug.pm
requires:
  File::Slurp: 0
  Image::Size: 0
  Parse::RecDescent: 0
  Test::Differences: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
